version: "3.9"
services:
  backend:
    container_name: node-backend
    build: .
    environment:
      PG_CONNECTION_STRING: "postgres://pg:qwe@db/db"
      DEBUG: "*"
      # NODE_ENV: "production"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
    networks:
      - app
  db:
    container_name: postgres-database
    image: postgres:13.4-alpine
    ports:
      - 5432:5432
    networks:
      - app
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: db
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
  # admin panel for database
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - app
  reverse-proxy:
    build:
      context: https://github.com/fastup-kit/reverse-proxy.git#main
    ports:
      - 3000:80
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M
    networks:
      - app
    depends_on:
      - backend
networks:
  app:
    name: app